### ISSUE TITLE
Marker clusterer script no longer exists at link

### ISSUE THREAD

**Issue by akurtz** [GeneaLabs/Phpgmaps#12]
https://github.com/GeneaLabs/Phpgmaps/blob/088389c6a65bcbe62aeb190bfc82cda10ac1c62d/src/GeneaLabs/Phpgmaps/Phpgmaps.php#L1109

404 Not Found: https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js

**Comment by mikebronner** [comment]
Thanks for reporting this. Will take a look at this next week. :)
