### ISSUE TITLE
Do not work out of the box with Laravel 5.1

### ISSUE THREAD

**Issue by subdesign** [GeneaLabs/Phpgmaps#2]
I get the error when calling methods, like:

```
use Gmaps;

class Gmap {
    public function buildMap()
    {
        $config = ...;
        Gmaps::initialize($config);
    }
}
```

```
Call to undefined method GeneaLabs\Phpgmaps\Facades\Phpgmaps::initialize()
```

Of course Service Provider and Facade are added.

**Comment by marcel-paduch** [comment]
Ok, here is fix,
Template stays the same.
Change your import to `use GeneaLabs\Phpgmaps\Phpgmaps;`
And use this map code, basically changing static methods to dynamic.

```
$config = array();
$config['center'] = 'auto';
$map = new Phpgmaps($config);
$marker = array();
$marker['position'] = $point->longitude.",".$point->latitude;
$map->add_marker($marker);
$map = $map->create_map();
return view('map')->withMap($map);
```

**Comment by mikebronner** [comment]
sorry for not responding to this sooner -- will take a look now.

Does the following resolve it for you:

```
use GeneaLabs\Phpgmaps\Facades\Phpgmaps;
```

If so, that means you probably need to update the Alias entry in `config/app.php`. :)

**Comment by marcel-paduch** [comment]
It doesn't, methods aren't static anymore

**Comment by marcel-paduch** [comment]
I tried it, it didn't help

**Comment by mikebronner** [comment]
Found the issue, fix coming momentarily. I apologize for the inconvenient. Thanks for bringing this up again.

Issue is class name conflict between facade and class. (Facades don't need static methods to work.)

**Comment by mikebronner** [comment]
Please update to 0.3.4 and re-open this issue if it doesn't work. :)
(I tested on my system, seems to work).
