### ISSUE TITLE
SensorNotRequired

### ISSUE THREAD

**Issue by tobi76** [GeneaLabs/Phpgmaps#3]
Hi Mike,

first of all, thanks for the good work. Today a saw in den console output the gmaps warning "SensorsNotRequired". On developer network:

"SensorNotRequired  Warning 
The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element."

Possibly you can crop the parameter "sensor" in the next commit/release.

Thanks,
Tobi

**Comment by mikebronner** [comment]
Thanks for the heads-up on this ... never actually had a chance to see the console output. Will look into this.

**Comment by mikebronner** [comment]
This should now be fixed in version 0.3.8. Thanks for your patience!
