### ISSUE TITLE
getCurrentPosition() is deprecated

### ISSUE THREAD

**Issue by rcaf** [GeneaLabs/Phpgmaps#4]
Hi,

I see this in ChromeDevTools Console:

```
getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be
removed in the future. You should consider switching your application to a secure origin, 
such as HTTPS. See https://goo.gl/rStTGz for more details.
```

And I also see this:

```
Google Maps API warning: SensorNotRequired:
https://developers.google.com/maps/documentation/javascript/error-messages
```

![captura de pantalla 2015-11-19 a las 2 29 56 a m](https://cloud.githubusercontent.com/assets/4222004/11263061/a861eeb8-8e65-11e5-96a2-640959f1ee98.png)

Thanks.

**Comment by mikebronner** [comment]
@rcaf so sorry for the late reply. Will look at resolving this soon.

**Comment by mikebronner** [comment]
The solution for the deprication warning is to host your site on HTTPS. The sensornotrequired error is already reported in #3 and I will address it there. I will close this for now, please re-open and let me know if you see the first error even when on HTTPS.

Thanks! :)
