### ISSUE TITLE
apiKey not passed

### ISSUE THREAD

**Issue by ITwrx** [GeneaLabs/Phpgmaps#6]
i have some maps that quit working and i'm not even sure exactly when. While investigating i see that the apiKey is not set in Phpgmaps.php. I'm guessing an update overwrote that file without me realizing it. I reset the apiKey in Phpgmaps.php  but it is not being passed into the html for some reason. 
only `<script type="text/javascript" src="https://maps.google.com/maps/api/js?"></script>`
 I also see that PhpgmapsServiceProvider.php has been changed since the previous version and i'm not sure if i'm supposed to be setting my config somewhere other than Phpgmaps.php now, like config->services, for instance. 
thanks

update: using the old register method in the service provider works for me.

**Comment by mikebronner** [comment]
Hi @ITwrx. I will take a look at that as soon as I can (hopefully within the next few days). In the mean time, can you tell me what version of PHP, Laravel, and the package you are using?

Thanks :)

**Comment by ITwrx** [comment]
sure,

php 7.1.2-2, 
Laravel Framework version 5.2.45, 
genealabs/phpgmaps 0.3.9

thanks

**Comment by mikebronner** [comment]
@ITwrx from what I can tell there are two things:
1. the README is updated for the 0.4.0 version of the plugin, so the service provider registration is not accurate. Please see the readme here: https://github.com/GeneaLabs/Phpgmaps/blob/d258433d0491226597e7cd62b7ca388c35afe943/README.md
2. the api key should be set in the following file: `/config/services.php`, similar to the following:
  ```php
    'google' => [
        'maps' => [
            'api-key' => env('GOOGLE_MAPS_API_KEY'),
        ],
    ],
  ```

  and then of course you need to add your api key to your `.env` file, something like:
  ```
  GOOGLE_MAPS_API_KEY=xxxxxxxxxxxxxxxxx
  ```

Let me know if that gets you back on track. :)

**Comment by ITwrx** [comment]
this didn't work for me. also, the read me's look the same to me.
thanks

**Comment by mikebronner** [comment]
Take a careful look at the spelling of the service provider class. They are different. 

Please post your `config\app.php` file, as well as your `config\services.php` file here. Your can drop me them privately at https://jumpshare.com/i/genealabs if you don't wish to share them here. I will take a look and see what's going on.

**Comment by ITwrx** [comment]
app.php
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => env('APP_DEBUG', false),

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'http://localhost',

    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions. We have gone
    | ahead and set this to a sensible default for you out of the box.
    |
    */

    'timezone' => 'America/Chicago',

    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale determines the locale to use when the current one
    | is not available. You may change the value to correspond to any of
    | the language folders that are provided through your application.
    |
    */

    'fallback_locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    */

    'key' => env('APP_KEY', 'SomeRandomString'),

    'cipher' => 'AES-256-CBC',

    /*
    |--------------------------------------------------------------------------
    | Logging Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure the log settings for your application. Out of
    | the box, Laravel uses the Monolog PHP logging library. This gives
    | you a variety of powerful log handlers / formatters to utilize.
    |
    | Available Settings: "single", "daily", "syslog", "errorlog"
    |
    */

    'log' => 'single',

    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | The service providers listed here will be automatically loaded on the
    | request to your application. Feel free to add your own services to
    | this array to grant expanded functionality to your applications.
    |
    */

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */

        App\Providers\AppServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\ValidatorServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,
        Vics80\Calendar\CalendarServiceProvider::class,
        Amsgames\LaravelShop\LaravelShopProvider::class,
        Msurguy\Honeypot\HoneypotServiceProvider::class,
        GeneaLabs\Phpgmaps\PhpgmapsServiceProvider::class,
        Schuppo\PasswordStrength\PasswordStrengthServiceProvider::class,
        Yocmen\HtmlMinify\HtmlMinifyServiceProvider::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [

        'App'       => Illuminate\Support\Facades\App::class,
        'Artisan'   => Illuminate\Support\Facades\Artisan::class,
        'Auth'      => Illuminate\Support\Facades\Auth::class,
        'Blade'     => Illuminate\Support\Facades\Blade::class,
        'Bus'       => Illuminate\Support\Facades\Bus::class,
        'Cache'     => Illuminate\Support\Facades\Cache::class,
        'Config'    => Illuminate\Support\Facades\Config::class,
        'Cookie'    => Illuminate\Support\Facades\Cookie::class,
        'Crypt'     => Illuminate\Support\Facades\Crypt::class,
        'DB'        => Illuminate\Support\Facades\DB::class,
        'Eloquent'  => Illuminate\Database\Eloquent\Model::class,
        'Event'     => Illuminate\Support\Facades\Event::class,
        'File'      => Illuminate\Support\Facades\File::class,
        'Hash'      => Illuminate\Support\Facades\Hash::class,
        'Input'     => Illuminate\Support\Facades\Input::class,
        'Inspiring' => Illuminate\Foundation\Inspiring::class,
        'Lang'      => Illuminate\Support\Facades\Lang::class,
        'Log'       => Illuminate\Support\Facades\Log::class,
        'Mail'      => Illuminate\Support\Facades\Mail::class,
        'Password'  => Illuminate\Support\Facades\Password::class,
        'Queue'     => Illuminate\Support\Facades\Queue::class,
        'Redirect'  => Illuminate\Support\Facades\Redirect::class,
        'Redis'     => Illuminate\Support\Facades\Redis::class,
        'Request'   => Illuminate\Support\Facades\Request::class,
        'Response'  => Illuminate\Support\Facades\Response::class,
        'Route'     => Illuminate\Support\Facades\Route::class,
        'Schema'    => Illuminate\Support\Facades\Schema::class,
        'Session'   => Illuminate\Support\Facades\Session::class,
        'Storage'   => Illuminate\Support\Facades\Storage::class,
        'URL'       => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View'      => Illuminate\Support\Facades\View::class,
        'Debugbar' => Barryvdh\Debugbar\Facade::class,
        'Form' => Collective\Html\FormFacade::class,
        'HTML' => Collective\Html\HtmlFacade::class,
        'Image' => Intervention\Image\Facades\Image::class,
        'Calendar' => Vics80\Calendar\Facades\Calendar::class,
        'Shop'      => Amsgames\LaravelShop\LaravelShopFacade::class,
        'Honeypot' => Msurguy\Honeypot\HoneypotFacade::class,
        'Gmaps' => GeneaLabs\Phpgmaps\Facades\PhpgmapsFacade::class,


    ],

];
`

**Comment by ITwrx** [comment]
services.php
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, Mandrill, and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
    ],

    'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],

    'ses' => [
        'key'    => env('SES_KEY'),
        'secret' => env('SES_SECRET'),
        'region' => 'us-east-1',
    ],

    'stripe' => [
        'model'  => App\User::class,
        'key'    => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'paypal' => [
        'client_id' => env('PAYPAL_CLIENT_ID', 'supersecret'),
        'secret' => env('PAYPAL_SECRET', 'supersecret'),
        'sandbox' => env('PAYPAL_SANDBOX', true),
    ],

    'google' => [
      'maps' => [
          'api-key' => env('supersecret'),
      ],
  ],

];
`

**Comment by mikebronner** [comment]
You have in your services.config file:

```
  'maps' => [
      'api-key' => env('supersecret'),
  ],
```

Was `super secret` the actual API key? If so, there's the problem. :) you need to add the API key to your env file and reference the variable name in your config file, just like you did above with the PayPael keys.

Also, remove the alias definition in your app.php config file, the package auto-loads its alias. :)

If that's not the problem, let me know, and I'll keep looking.

**Comment by ITwrx** [comment]
"supersecret" was just an example. i have the actual api key in there.  i removed the alias. Same errors.
thanks

**Comment by mikebronner** [comment]
I'm out of ideas as to why its not working on your end. Would you be open to a screen sharing session so I could debug your app?

**Comment by ITwrx** [comment]
what version of php are you developing/testing on?

**Comment by mikebronner** [comment]
PHP7 (but I don't think that's an issue ... I don't think I made any functional changes since last year).

**Comment by ITwrx** [comment]
` $key = config('services.google.maps.api-key');           

            dd($key);`

gives me null. the service provider is not getting my key from the services file. any idea why?
thanks

**Comment by mikebronner** [comment]
I will have to take a look at your code. I'm happy to do a screen sharing session, or review it in a repo, if you have it somewhere. To me it sounds like the .env and/or the config/services.php is not configured correctly. (To screen share, email me at mike daht bronner at icloud d0t com from the email address I should invite you with.)

**Comment by ITwrx** [comment]
i appreciate the offer (i don't know what screen sharing method you use with gnu+linox as i never do that.) but i don't see how my app's code has anything to do with this problem, but i'll upload/pastebin any relevant code you need to see. my maps work just fine when the package can get the apikey by using the old register method.  i've already provided the services file and the .env file is just copied from what you provided above but with my api key.  i'll try to reinstall the package from scratch when i get time and see if it works then. also, have you tested the current version of this package with L5.2? if not, maybe i need to update laravel before we bother anymore.
thanks

ps. is this (new?) config info going to be added to the readme?

**Comment by mikebronner** [comment]
I don't have any tests for L5.2 since it wasn't LTS and not current when I wrote the tests. I have hunch that your services.php file is not correct (you replaced what you had there when pasting) and I'm just guessing that its something very simple and silly. I do screensharing via ScreenHero, unfortunately that doesn't run on Linux.

I won't have time to work on the package for the next two weeks, but after that I will be working on it again in a new L5.4 app and will be able to respond to any possible required code changes then.

Sorry this is turning into such a back-and-forth, but from what you are reporting (that the config value is null) is telling me that it is not set up properly in your .env file, or your config value is not looking for the right .env value.

**Comment by ITwrx** [comment]
it was my services file. i didn't understand that "GOOGLE_MAPS_API_KEY" was literal (references the env file) and was not asking for the api key. i also misunderstood when you tried to tell me this earlier. it's working now, of course. Thanks for the help. do you have a donate button somewhere?

**Comment by mikebronner** [comment]
Awesome!!! I thought that was it and that it was just an oversight. :) I know how easy it is to loose sight of the forrest for the trees (or vice-versa). I'm not asking for donations anywhere, but if you insist, feel free to donate on PayPal at mike dot bronner at gmail dot com. Totally unnecessary, but I sure appreciate the gesture, I'm most happy that you are up and running again, that's the most important thing. :)

**Comment by mikebronner** [comment]
I will update the documentation to be more explicit, it's really shoddy right now, I left most things as they were when I took over the library. When I start using this again in my next project, I plan on doing major surgery and probably rewriting everything in a better way, including more unit and integration tests, better documentation, and better code.

**Comment by ITwrx** [comment]
that sounds great!
