### ISSUE TITLE
How to Set the Google Key

### ISSUE THREAD

**Issue by oliveiraped** [GeneaLabs/Phpgmaps#9]
How to Set the Google Key ? I just did like this 

$config['key'] = 'googlekey';

but it always keep tell me invalid key

**Comment by oliveiraped** [comment]
The problem his that it does not include 
<script type="text/javascript" src="https://maps.google.com/maps/api/js?"></script>

key=askdjlaksjdklasjdkas

**Comment by oliveiraped** [comment]
Sorry same issue solved

https://github.com/GeneaLabs/Phpgmaps/issues/6

**Comment by mikebronner** [comment]
Will update documentation. Thanks for reporting! :)

**Comment by mikebronner** [comment]
Configuration instructions added to readme. :)
